# Generated by Django 3.2.8 on 2021-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20211124_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerinterminal',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='container_list_in_terminal', to='terminal.terminal'),
        ),
    ]
