# Generated by Django 3.2.8 on 2021-11-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway_bill', '0018_auto_20211123_1206'),
        ('terminal', '0003_alter_containerinterminal_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerinterminal',
            name='container',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_in_terminal', to='railway_bill.container'),
        ),
        migrations.AlterField(
            model_name='containerinterminal',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_list_in_terminal', to='terminal.terminal'),
        ),
    ]
