# Generated by Django 3.2.8 on 2021-11-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0007_auto_20211118_1204'),
        ('railway_bill', '0018_auto_20211123_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived', models.BooleanField(default=False)),
                ('cargo_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_statuses', to='railway_bill.container')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_status', to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='SealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seal_images/')),
                ('container_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seal_images', to='container_status.containerstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/containers/')),
                ('container_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_documents', to='container_status.containerstatus')),
            ],
        ),
    ]
